// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwyttzfnntyebfiauvis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3eXR0emZubnR5ZWJmaWF1dmlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNzY4NzIsImV4cCI6MjA2MTc1Mjg3Mn0.clOf8riJzFrfTxKGH61hQ32JdHhtkP3o8HNiziuF0Gc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);